FROM debian:trixie-slim AS ffmpeg-builder

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    tar \
    xz-utils && \
    rm -rf /var/lib/apt/lists/*

ARG TARGETARCH
ARG FFMPEG_VERSION=9.0

ENV TARGETARCH=${TARGETARCH}
ENV FFMPEG_VERSION=${FFMPEG_VERSION}

RUN case "${TARGETARCH}" in \
      "amd64") ARCH_NAME="64" ;; \
      "arm64") ARCH_NAME="arm64" ;; \
      *) echo "Unsupported architecture: ${TARGETARCH}" && exit 1 ;; \
    esac && \
    URL="https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-n${FFMPEG_VERSION}-latest-linux${ARCH_NAME}-lgpl-${FFMPEG_VERSION}.tar.xz" && \
    echo "Fetching: ${URL}" && \
    curl -fsSL "${URL}" -o /tmp/ffmpeg.tar.xz && \
    mkdir -p /tmp/extracted && \
    tar -xJf /tmp/ffmpeg.tar.xz -C /tmp/extracted --strip-components=1 && \
    mv /tmp/extracted/bin/ffmpeg /tmp/ffmpeg && \
    mv /tmp/extracted/bin/ffprobe /tmp/ffprobe && \
    rm -rf /tmp/extracted /tmp/ffmpeg.tar.xz

FROM debian:trixie-slim AS runtime
LABEL org.opencontainers.image.source="https://github.com/thatgurkangurk/thumbnail-generator"

ARG TARGETARCH

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    tzdata && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /thumbnail

ARG APP_VERSION
ENV APP_VERSION=$APP_VERSION

ARG UID=1000
ARG GID=1000

RUN groupadd -g ${GID} thumbnail && \
    useradd -u ${UID} -g thumbnail -s /usr/sbin/nologin thumbnail

COPY --from=ffmpeg-builder /tmp/ffmpeg /usr/local/bin/ffmpeg

COPY ./deploy-out/${TARGETARCH}/thumbnail-generator /usr/local/bin/thumbnail-generator

USER thumbnail

EXPOSE 3000

ENTRYPOINT ["/usr/local/bin/thumbnail-generator"]
